services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: v2ex-remote:${ARCH_TAG:-latest}
    ports:
      - "${HOST_IP:-0.0.0.0}:${HOST_PORT:-5000}:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV_NAME=${APP_ENV_NAME:-PROD}
    volumes:
      - ./:/app
    command: ["/usr/local/bin/gunicorn", "-b", "0.0.0.0:5000", "-w", "${GUNICORN_WORKERS:-4}", "remote.app:app"]
