name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Lint:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: PreCommit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  Test:
    name: PyTest
    needs: [Lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip setuptools
          pip install -r requirements.txt -r requirements-test.txt
          python -c "import sys; print(sys.version)"
          pip list
      - name: Test
        run: |
          . venv/bin/activate
          pytest -sx -vvv --cov=. tests/

  Docker-Build-And-Push:
    name: Docker-Build-And-Push
    needs: [Test]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: remote
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # can't get git tag if without ${{ github.sha }}
        with:
          ref: ${{ github.sha }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare docker tag name with git tag
        if: ${{ github.ref_type  == 'tag' }}
        run: echo "TAG=${{ github.ref_name }}" >>${GITHUB_ENV}

      - name: Check Image Tag
        run: |
          echo "use commit hash as tag: ${{ github.sha }}"
          echo "use commit tag as tag: $TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build And Push
        uses: docker/build-push-action@v2
        env:
          CR_URL: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.CR_URL }}:latest
            ${{ env.CR_URL }}:${{ github.sha }}
            ${{ env.CR_URL }}:${{ env.TAG || github.sha }}
